import { describe, expect, it } from 'vitest';
import {
  changedPackages,
  LOCKFILES,
  packageNameOf,
  packageRelations,
  readLockfile,
  Unreadable,
} from './index.js';

/**
 * One install, written four ways. Every fixture resolves the same three
 * packages and the same chain — `jest-environment-jsdom` rests on `jsdom`,
 * which rests on `whatwg-url` — so a reader that loses an edge, keeps a
 * workspace, or collapses two names into one fails on the same assertions
 * regardless of which manager wrote it.
 */

const YARN_CLASSIC = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.10.4":
  version "7.24.7"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.24.7.tgz#882fd9e"
  integrity sha512-BcYH1CVJBO9==
  dependencies:
    picocolors "^1.0.0"

jest-environment-jsdom@^29.0.0:
  version "29.7.0"
  resolved "https://registry.yarnpkg.com/jest-environment-jsdom/-/x-29.7.0.tgz#d1b1"
  integrity sha512-k9iQbsf9==
  dependencies:
    jsdom "^24.0.0"

jsdom@^24.0.0:
  version "24.1.0"
  resolved "https://registry.yarnpkg.com/jsdom/-/jsdom-24.1.0.tgz#abc"
  integrity sha512-6gpM7pRXC==
  dependencies:
    whatwg-url "^14.0.0"
  optionalDependencies:
    canvas "^2.11.2"

whatwg-url@^14.0.0:
  version "14.0.0"
  resolved "https://registry.yarnpkg.com/whatwg-url/-/whatwg-url-14.0.0.tgz#def"
  integrity sha512-1lfMEm2==
`;

const YARN_BERRY = `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: 10c0

"@babel/code-frame@npm:^7.0.0, @babel/code-frame@npm:^7.10.4":
  version: 7.24.7
  resolution: "@babel/code-frame@npm:7.24.7"
  dependencies:
    picocolors: "npm:^1.0.0"
  checksum: 10c0/ab0af539
  languageName: node
  linkType: hard

"jest-environment-jsdom@npm:^29.0.0":
  version: 29.7.0
  resolution: "jest-environment-jsdom@npm:29.7.0"
  dependencies:
    jsdom: "npm:^24.0.0"
  checksum: 10c0/29d6f7b2
  languageName: node
  linkType: hard

"jsdom@npm:^24.0.0":
  version: 24.1.0
  resolution: "jsdom@npm:24.1.0"
  dependencies:
    whatwg-url: "npm:^14.0.0"
  checksum: 10c0/0f4d87a3
  languageName: node
  linkType: hard

"ui@workspace:packages/ui":
  version: 0.0.0-use.local
  resolution: "ui@workspace:packages/ui"
  dependencies:
    jsdom: "npm:^24.0.0"
  languageName: unknown
  linkType: soft

"whatwg-url@npm:^14.0.0":
  version: 14.0.0
  resolution: "whatwg-url@npm:14.0.0"
  checksum: 10c0/6b1e0d34
  languageName: node
  linkType: hard
`;

const PNPM = `lockfileVersion: '9.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

importers:

  .:
    dependencies:
      jest-environment-jsdom:
        specifier: ^29.0.0
        version: 29.7.0
  packages/ui:
    dependencies:
      jsdom:
        specifier: ^24.0.0
        version: 24.1.0

packages:

  '@babel/code-frame@7.24.7':
    resolution: {integrity: sha512-BcYH1CVJBO9==}
    engines: {node: '>=6.9.0'}

  jest-environment-jsdom@29.7.0:
    resolution: {integrity: sha512-k9iQbsf9==}
    engines: {node: '>=14'}

  jsdom@24.1.0:
    resolution: {integrity: sha512-6gpM7pRXC==}

  whatwg-url@14.0.0:
    resolution: {integrity: sha512-1lfMEm2==}

snapshots:

  '@babel/code-frame@7.24.7':
    dependencies:
      picocolors: 1.0.1

  jest-environment-jsdom@29.7.0(bufferutil@4.0.8):
    dependencies:
      jsdom: 24.1.0

  jsdom@24.1.0:
    dependencies:
      whatwg-url: 14.0.0
    optionalDependencies:
      canvas: 2.11.2

  whatwg-url@14.0.0: {}
`;

const NPM = JSON.stringify(
  {
    name: 'root',
    lockfileVersion: 3,
    packages: {
      '': { name: 'root', dependencies: { 'jest-environment-jsdom': '^29.0.0' } },
      'packages/ui': { name: 'ui', version: '0.0.0' },
      'node_modules/ui': { resolved: 'packages/ui', link: true },
      'node_modules/@babel/code-frame': {
        version: '7.24.7',
        resolved: 'https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.24.7.tgz',
        integrity: 'sha512-BcYH1CVJBO9==',
        dependencies: { picocolors: '^1.0.0' },
      },
      'node_modules/jest-environment-jsdom': {
        version: '29.7.0',
        resolved: 'https://registry.npmjs.org/jest-environment-jsdom/-/x-29.7.0.tgz',
        integrity: 'sha512-k9iQbsf9==',
        dependencies: { jsdom: '^24.0.0' },
      },
      'node_modules/jsdom': {
        version: '24.1.0',
        resolved: 'https://registry.npmjs.org/jsdom/-/jsdom-24.1.0.tgz',
        integrity: 'sha512-6gpM7pRXC==',
        dependencies: { 'whatwg-url': '^14.0.0' },
        optionalDependencies: { canvas: '^2.11.2' },
      },
      'node_modules/whatwg-url': {
        version: '14.0.0',
        resolved: 'https://registry.npmjs.org/whatwg-url/-/whatwg-url-14.0.0.tgz',
        integrity: 'sha512-1lfMEm2==',
      },
    },
  },
  undefined,
  2,
);

const FIXTURES = [
  ['yarn.lock', YARN_CLASSIC, 'yarn-classic'],
  ['yarn.lock', YARN_BERRY, 'yarn-berry'],
  ['pnpm-lock.yaml', PNPM, 'pnpm'],
  ['package-lock.json', NPM, 'npm'],
] as const;

describe.each(FIXTURES)('%s as %s', (file, text, format) => {
  const lock = readLockfile(file, text);

  it('names the reader that answered', () => {
    expect(lock.format).toBe(format);
  });

  it('resolves every package once, by name', () => {
    expect([...lock.identities.keys()].sort()).toEqual([
      '@babel/code-frame',
      'jest-environment-jsdom',
      'jsdom',
      'whatwg-url',
    ]);
  });

  it('carries the chain a transitive bump has to travel', () => {
    expect(packageRelations(lock)).toContainEqual(['jest-environment-jsdom', 'jsdom']);
    expect(packageRelations(lock)).toContainEqual(['jsdom', 'whatwg-url']);
  });

  it('drops an edge to something the lockfile never resolved', () => {
    // `picocolors` and `canvas` are named as dependencies and installed by no
    // entry here, so they are packages nothing can change.
    expect(packageRelations(lock).map(([, to]) => to)).not.toContain('picocolors');
    expect(packageRelations(lock).map(([, to]) => to)).not.toContain('canvas');
  });

  it('leaves the workspace to the file graph', () => {
    expect(lock.identities.has('ui')).toBe(false);
  });

  it('identifies a package by something that moves when the install does', () => {
    expect(lock.identities.get('jsdom')).toContain('24.1.0');
  });
});

describe('what moved', () => {
  it('is nothing when the same text is read twice', () => {
    const before = readLockfile('yarn.lock', YARN_CLASSIC);
    const after = readLockfile('yarn.lock', YARN_CLASSIC);
    expect(changedPackages(before, after)).toEqual([]);
  });

  it('is the one package whose resolution moved', () => {
    const before = readLockfile('yarn.lock', YARN_CLASSIC);
    const after = readLockfile('yarn.lock', YARN_CLASSIC.replace('24.1.0', '24.1.1'));
    expect(changedPackages(before, after)).toEqual(['jsdom']);
  });

  it('counts a package that left', () => {
    const before = readLockfile('pnpm-lock.yaml', PNPM);
    const after = readLockfile('pnpm-lock.yaml', PNPM.replace(/\n  whatwg-url@14\.0\.0:\n[^\n]*\n/, '\n'));
    expect(changedPackages(before, after)).toContain('whatwg-url');
  });

  it('is everything when the project switched package managers', () => {
    const before = readLockfile('yarn.lock', YARN_CLASSIC);
    const after = readLockfile('pnpm-lock.yaml', PNPM);
    expect(changedPackages(before, after)).toHaveLength(4);
  });

  it('is nothing when only a workspace version churned', () => {
    const before = readLockfile('yarn.lock', YARN_BERRY);
    const after = readLockfile('yarn.lock', YARN_BERRY.replace('0.0.0-use.local', '0.0.1-use.local'));
    expect(changedPackages(before, after)).toEqual([]);
  });
});

describe('what it refuses', () => {
  it('names a lockfile version it has never seen', () => {
    expect(() => readLockfile('pnpm-lock.yaml', "lockfileVersion: '5.4'\n")).toThrow(/lockfileVersion 5\.4/);
  });

  it('names a yarn metadata version below the format it reads', () => {
    expect(() => readLockfile('yarn.lock', '__metadata:\n  version: 3\n')).toThrow(/__metadata.version 3/);
  });

  it('names a file that is not a lockfile at all', () => {
    expect(() => readLockfile('package.json', '{}')).toThrow(Unreadable);
  });

  it('refuses a package-lock that is not JSON', () => {
    expect(() => readLockfile('package-lock.json', 'not json')).toThrow(/is not JSON/);
  });

  it('refuses rather than guessing at a construct it does not read', () => {
    expect(() => readLockfile('pnpm-lock.yaml', "lockfileVersion: '9.0'\npackages:\n  a: &anchor\n")).toThrow(
      Unreadable,
    );
  });
});

describe('the names a caller looks for, and the name a descriptor carries', () => {
  it('lists the lockfiles in the order a caller should look for them', () => {
    // A repository with two has switched managers and not finished, and the
    // tie is broken the way the managers break it themselves.
    expect([...LOCKFILES]).toEqual(['pnpm-lock.yaml', 'yarn.lock', 'package-lock.json', 'npm-shrinkwrap.json']);
  });

  it('reads the package out of a descriptor at the first @ after position zero', () => {
    expect(packageNameOf('lodash@npm:^4.17.21')).toBe('lodash');
    expect(packageNameOf('@babel/core@7.24.7')).toBe('@babel/core');
    // An alias: the importers write `foo`, so the last @ would be the wrong one.
    expect(packageNameOf('foo@npm:@scope/bar@1.0.0')).toBe('foo');
  });
});
