import json
d = {
"acquisition/collector-contract/README.md": "Defines the interface a user-supplied capture module implements to list UI states and capture each, one at a time; a state that fails becomes a named failure, never an exception.",
"acquisition/deferred-capture/README.md": "Packages a captured UI state with its markup, trimmed styles, fonts and inlined resources so a browserless process can hand it to a pinned painting machine; never compares or paints.",
"acquisition/host-adapters/README.md": "Drives Storybook or a served page to each named UI state over the host's own switching channel and captures it; never mounts components, reloads per state, or follows links.",
"acquisition/live-extraction/README.md": "Reads a live element's DOM and only the CSS rules that can apply to it, within what the capturing environment can observe; marks ignored areas instead of deleting them.",
"acquisition/page-agent/README.md": "Sends capture requests into the browser page and returns plain serialized results once assets stop changing; passes settings by id, never live objects or functions.",
"acquisition/subject-plan/README.md": "Lists the UI states a run intends to capture in a machine-independent order, naming each one it refuses; does not decide which ones a code change affected.",
"acquisition/suite-observation/README.md": "Captures a UI state from an element locator inside an existing test that already navigated and waited, restoring any markers it adds; builds no capture plan of its own.",
"acquisition/value-subject/README.md": "Treats plain data never rendered, such as an API response or route table, as something to capture and compare; needs no browser, and refuses unserializable values by name.",
"adjudication/attribution/README.md": "Groups changed pixels into regions and maps each to the responsible component and its source line, ranking root causes above what they pushed aside; never guesses nearest box.",
"adjudication/comparison/README.md": "Runs one UI state's two captures through a fixed sequence of exclusions, checks and attributions, and commits to a single outcome word with an explanation; does not aggregate results.",
"adjudication/composition/README.md": "Links UI states within one run through the components they share, showing which watch the same code, which disagree, and what explains each change; uses no reference image.",
"adjudication/difference/README.md": "Diffs two structural snapshots into change lists sorted by severity category and grouped by originating cause; says what moved but never whether it matters.",
"adjudication/ignores/README.md": "Applies user rules declaring differences that will not be examined, requiring a reason and optional expiry, and accounts for every rule each run, including rules that matched nothing.",
"adjudication/inspection/README.md": "Checks a single stored capture for defects with nothing to compare against, producing findings attributed to where markup was written; never produces pass/fail outcomes.",
"adjudication/pixel-comparison/README.md": "Compares two images under lenient and strict per-pixel rules, producing changed-pixel counts, a change mask, a viewable diff image and a shape signature; never names components.",
"adjudication/sensitivity/README.md": "Decides up front, from cheap component hashes, which change categories a UI state is checked on, skipping expensive work; when unsure it errs toward reporting changes.",
"adjudication/variations/README.md": "Compares a UI state to the sibling state it declares itself a variant of, such as dark mode, and records that difference separately; reaches no pass/fail outcome.",
"materialization/browser-renderer/README.md": "Paints a prepared page into a screenshot using one browser it launches with a declared recipe, intercepting network requests; never uses the page captures were taken from.",
"materialization/document-assembly/README.md": "Turns a captured page description into a ready-to-paint HTML document with styles in their original order; fetches nothing, waits for nothing, pure transformation.",
"materialization/in-place-raster/README.md": "Takes screenshots from the browser an existing test suite already controls and records how that browser was launched; adds no interventions and never retries for agreement.",
"materialization/remote-hop/README.md": "Places a screenshot renderer behind a network connection transparently, batching overlapping requests; returns broken pages as failures, never blank images.",
"materialization/render-deferral/README.md": "Skips painting when an image already exists for the same page content and rendering setup; purely a speed-up, never affects correctness.",
"materialization/renderer-contract/README.md": "Declares the interface for anything that turns a captured page into an image, including stating its setup before painting; knows nothing about stored reference images.",
"materialization/renderer-identity/README.md": "Combines every input that can affect a pixel, such as browser, fonts and scale, into one value so images from different setups are never compared.",
"normalization/call-site/README.md": "Keeps the file, line and column that created each element and maps compiled positions back to original source using source maps; reads no framework internals.",
"normalization/component-boundaries/README.md": "Splits the rendered tree by owning component and hashes each component's own content, with nested components as named placeholders; never hashes file paths.",
"normalization/declaration-index/README.md": "Answers which file declares a component by name, listing all candidates when several match instead of picking one; ranks nothing.",
"normalization/digests/README.md": "Serializes a structure canonically and hashes it so identity depends on content, not location or commit; hashes each change category separately and omits unknown fields.",
"normalization/normalizer/README.md": "Applies one versioned rule set to a raw DOM capture to produce the canonical snapshot all later checks read; never decides what counts as a difference.",
"normalization/provenance/README.md": "Reads framework metadata on each rendered node to record which components enclose it and which component wrote it, keeping both links; reads no layout or styles.",
"normalization/wiring/README.md": "Reads the UI framework's own description of a component, such as its hooks and held state, as evidence; attaches facts only to the component's root element.",
"presentation/acquisition-readiness/README.md": "Holds a chosen region of the interface still and collects only the data a layout-quality analysis needs, waiting for that region rather than the whole page.",
"presentation/hierarchy-contract/README.md": "Checks a product-declared description of what each spacing relationship means and reports where two neighbouring meanings became visually indistinguishable; refuses incomplete declarations.",
"presentation/paint-overlay/README.md": "Draws markers for already-measured layout findings over the live page, one owner or finding at a time; never recaptures or changes measurements.",
"presentation/presentation-graph/README.md": "Builds a graph of elements, relations, clusters and repeated patterns from one capture to measure grouping, spacing, alignment and emphasis; produces nothing without layout data.",
"presentation/presentation-signal/README.md": "Compares two captures' layout analyses to list visual-structure problems introduced, fixed or unchanged; separate from pass/fail regression outcomes.",
"presentation/relationship-findings/README.md": "Flags a small fixed set of layout defects, like collapsing spacing, a misaligned peer or flattened emphasis, each pinned to the element owning that relationship.",
"presentation/structural-reading/README.md": "Serves an existing layout analysis at a chosen scope, one container, one subtree or one visual flow, without capturing the interface again.",
"reach/closure/README.md": "Hashes each file together with the hashes of everything it depends on, proving sameness without git refs or diffs; treats cycles as one unit.",
"reach/crossings/README.md": "Stores which test files executed which regions of instrumented source code and answers queries over that record; treats an unobserved path as unknown, not impossible.",
"reach/installed/README.md": "Compares the lockfile at two commits to find which packages changed, tracing indirect upgrades to dependents; an unreadable lockfile widens the test run.",
"reach/instrument/README.md": "Splits a source module into regions and inserts a lightweight probe before each, keeping line numbers intact; an unparseable module yields no result, not an empty one.",
"reach/journey/README.md": "Tags one test execution with a single opaque id across every process it touches, then merges what each process reported into one path; bounded by execution, not time.",
"reach/relations/README.md": "Holds the file and package dependency graph as one bidirectional structure and walks it either way, recording how each node was reached; performs no I/O.",
"reach/selection/README.md": "Picks which UI states and tests a code change could affect using import structure and recorded test coverage, over-including when unsure and listing everything it skipped.",
"reach/source-index/README.md": "Keeps a layered index of the checkout's parsed files, updated incrementally, so readers query it instead of rescanning; marks unreadable files as unknown.",
"reach/source-scan/README.md": "Walks the repository once, recording each file's resolved imports, content hash and declared components; decides where an import points, never what counts as one.",
"reach/story/README.md": "Turns the order one test visited source code into a numbered, page-sized route through declarations, read in parts; a readable map, not a full trace.",
"report/agent-surface/README.md": "Exposes a run's results to AI agents as read-only query tools, ordered to answer the useful questions first; never acts or changes anything.",
"report/docket/README.md": "Folds a run into actionable items, one per root cause, with everything that moved because of it counted under it; produces no text itself.",
"report/exit-code/README.md": "Reduces a run to one process exit code, keeping 'nothing to do', 'needs a human decision' and 'run broke' distinct.",
"report/intent-adjudication/README.md": "Compares a finished run against changes the author declared beforehand, showing which happened, which changed nothing, and what changed unclaimed; never alters outcomes or gates.",
"report/person-reading/README.md": "Renders the results file for people as terminal text, JSON, or one self-contained HTML page; never re-runs, filters out, or adds its own conclusions.",
"report/proposal-comment/README.md": "Writes the actionable-items summary as one pull request comment, found by a hidden marker and updated in place; posts only when the check fails.",
"report/run-report/README.md": "Defines the versioned results file a run leaves behind, listing every UI state, outcome, cause and unobserved item, openable without installing anything else.",
"report/shard-merge/README.md": "Merges results from parallel partial runs into one, refusing by name when shards disagree on setup; states excluded by every shard become failures.",
"retention/baseline-files/README.md": "Stores reference images on disk in folders partitioned by rendering setup, either in a runner-owned directory or tracked with a branch; rejects placeholder pointer files.",
"retention/baseline-store/README.md": "Defines how reference images are looked up and validated regardless of storage backend; a store that cannot answer raises an operator error, never a test failure.",
"retention/changelog/README.md": "Reads commit history to explain why each stored reference image looks the way it does; read-only, and says when its answer was truncated.",
"retention/promotion/README.md": "Writes an approved new screenshot in as the reference image and appends the approval record; moves existing files only, never recreates them.",
"retention/readings/README.md": "Computes trends a single run cannot, such as how often a component changes, state flakiness and value drift, each phrased so it cannot be mistaken for a failure.",
"retention/record/README.md": "Appends what every run observed, including changed hashes and self-disagreements, to a permanent history, including quiet runs; stores without judging.",
"retention/remote-baselines/README.md": "Serves the same reference-image lookup over the network from both client and server sides, reading its data once per run; owns no storage itself.",
"retention/render-cache/README.md": "Caches screenshots this machine already painted, keyed by page content and rendering setup; failures only slow a run, never fail it.",
"review/build-store/README.md": "Stores one uploaded run's results and images on the approval server and serves them back as the reviewer's item list; recomputes nothing.",
"review/capability/README.md": "Decides which of a deployment's two access secrets a caller presented and whether it permits the requested route; carries no user names.",
"review/decision/README.md": "Records one person's accept or reject for one UI state in one build, and on accept promotes the uploaded screenshot to reference; writes nothing for rejections.",
"review/deployment-adapters/README.md": "Connects the single request handler to hosting platforms such as a serverless worker, framework route or socket without changing routes or responses.",
"review/identity/README.md": "Authenticates that a request comes from a named human so each decision carries a name; never authenticates machines and stores no accounts.",
"review/retention-sweep/README.md": "Deletes uploaded builds older than a stated age when asked, listing exactly what it removed; never touches long-term history.",
"review/review-router/README.md": "Handles every server request, authenticating first and checking permissions per route, returning typed refusal statuses; makes no outbound requests.",
"review/review-surface/README.md": "Web page showing a build to a person, causes first, then marked regions, then images, and collecting their answer under their name; holds no credentials.",
"runtime/announcements/README.md": "Relays moments when application code makes a decision to waits inside a test; listeners can never affect the code they observe.",
"runtime/attention/README.md": "Records which elements a test interacted with, in order, capturing who wrote each before the page changes; draws no conclusions.",
"runtime/channel/README.md": "Gives a process under test one local HTTP route to send signals back to the run that started it; stores and interprets nothing.",
"runtime/scenario-archive/README.md": "Stores the text of approved scenario runs by content hash, under a policy for access and expiry; treats expired items as missing, never reconstructed.",
"runtime/scenarios/README.md": "Records a path through named states, a starting condition, user actions and the resulting state after each, and compares two paths; never infers unobserved transitions.",
"runtime/watched-run/README.md": "Keeps a live view of a running test suite in a long-lived process, with a bounded buffer counting what it dropped; writes nothing to disk.",
"stability/arrival/README.md": "Decides whether a UI state has finished loading and refuses to capture one that has not; never diagnoses or fixes why.",
"stability/instability/README.md": "Turns disagreement between two captures that should match into a location: component, change category, changed style declarations and source line; never sets pass/fail.",
"stability/isolated-reading/README.md": "Recaptures a changed UI state in a fresh environment to tell a real change from leftovers of earlier states; runs only after the repeat-capture check.",
"stability/second-reading/README.md": "Captures a UI state twice, seconds apart in the same environment, to check it agrees with itself; cannot catch leaks that fire consistently.",
"stability/stabilization/README.md": "Freezes a UI state for capture using a named set of interventions, like pausing animations, recorded in the capture's identity; never masks content.",
"stability/standing-world/README.md": "Runs many UI states in one shared browser session without teardown, detecting and attributing cross-contamination between them instead of isolating each.",
}
import glob,os,re
base='.compass/variance-authority'
paths=sorted(os.path.relpath(p,base) for p in glob.glob(base+'/*/*/**/README.md',recursive=True))
assert set(paths)==set(d),(set(paths)^set(d))
blocks="acquisition adjudication materialization normalization presentation reach report retention review runtime stability".split()
bad=False
for k,v in d.items():
    n=len(v.split())
    if n>30: print('LONG',k,n);bad=True
    for b in blocks:
        if re.search(r'\b'+b+r'\b',v,re.I): print('BLOCK',k,b);bad=True
print(len(paths),len(d),'bad' if bad else 'ok')
json.dump(d,open(os.path.dirname(__file__)+'/sub_plain.json','w'),indent=1)
