import { readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import type { D1Like, D1PreparedLike } from './bindings.js';
import { INITIAL, MIGRATIONS, SCHEMA, SCHEMA_VERSION, applySchema } from './schema.js';

/**
 * The migrations `wrangler` applies and the arrays the tests run against are one
 * schema.
 *
 * Two hand-maintained copies is the oldest way to deploy a table the code does
 * not believe in, and the failure is silent in the worst direction: every test
 * passes against `SCHEMA`, and production has the other one. So the `.sql` files
 * are generated by `tools/tribunal-migrations.mjs` and this asserts they did not
 * drift — which they will the first time somebody adds a column to `schema.ts`
 * and forgets that a deployment reads a file.
 *
 * The second failure this guards is newer and quieter: a step added to `INITIAL`
 * rather than to `MIGRATIONS` reaches every fresh deployment and no existing
 * one, and nothing about it looks wrong until an operator upgrades and a route
 * starts answering `no such table`.
 */

const DIR = join(dirname(fileURLToPath(import.meta.url)), '../migrations');

/** One entry per generated file, in the order `wrangler` applies them. */
const FILES = readdirSync(DIR)
  .filter((name) => name.endsWith('.sql'))
  .sort();

describe('the D1 migrations are the schema', () => {
  const text = (file: string): string => readFileSync(join(DIR, file), 'utf8');

  it('carries every statement, in order, across the files together', () => {
    // Containment and ordering rather than re-parsing. Splitting a file back
    // into statements would need a `;` split, which is precisely what
    // `schema.ts` exists as a list to avoid — the semicolons inside a trigger's
    // `BEGIN … END` are part of the statement, and a test that cut them in half
    // would fail on a correct file and teach somebody to loosen this.
    const joined = FILES.map(text).join('\n');
    let at = -1;

    for (const statement of SCHEMA) {
      const found = joined.indexOf(statement.trim());
      expect(found, `missing from the migrations: ${statement.trim().slice(0, 60)}…`).toBeGreaterThan(-1);
      expect(found, `out of order: ${statement.trim().slice(0, 60)}…`).toBeGreaterThan(at);
      at = found;
    }
  });

  it('adds nothing the schema does not have', () => {
    // The other direction, and the one containment alone cannot see: a statement
    // hand-added to a migration would deploy a table no test knows about.
    const statementLines = FILES.map(text)
      .join('\n')
      .split('\n')
      .filter((line) => !line.startsWith('--') && line.trim() !== '').length;
    const schemaLines = SCHEMA.flatMap((statement) => statement.trim().split('\n')).length;

    expect(statementLines).toBe(schemaLines);
  });

  it('has one file per step, and no more', () => {
    expect(FILES.length).toBe(MIGRATIONS.length + 1);
    expect(FILES[0]).toBe('0001_initial.sql');
  });

  it('keeps the initial file at the version it shipped at', () => {
    // The whole point of the split. If a change lands in `INITIAL`, this file's
    // contents move — and `wrangler` will never run it again on a database that
    // has already applied it, so the change reaches new deployments only.
    expect(text('0001_initial.sql')).toContain(`Schema version ${SCHEMA_VERSION - MIGRATIONS.length}`);
    expect(INITIAL.some((statement) => statement.includes('CREATE TABLE changelog'))).toBe(false);
  });

  it('ends every step by writing the version that step lands on', () => {
    // A database left at a version whose shape it does not have is worse than
    // one that refused to migrate: every query afterwards is against a table
    // that may or may not exist, decided by where the deployment stopped.
    MIGRATIONS.forEach((statements, index) => {
      const version = SCHEMA_VERSION - MIGRATIONS.length + index + 1;
      expect(statements[statements.length - 1]).toContain(
        `UPDATE schema_version SET version = ${version}`,
      );
    });
  });

  it('names the version each file was generated from', () => {
    FILES.forEach((file, index) => {
      expect(text(file)).toContain(
        `Schema version ${SCHEMA_VERSION - MIGRATIONS.length + index}`,
      );
    });
  });

  it('says it is generated, so nobody edits it by hand', () => {
    // The comment is the only thing standing between these files and somebody
    // fixing production in one, which would pass every test in the repository.
    for (const file of FILES) expect(text(file)).toContain('Do not edit');
  });

  it('applies the complete schema as one batch', async () => {
    const prepared: D1PreparedLike = {
      bind: () => prepared,
      first: async () => null,
      all: async () => ({ results: [] }),
      run: async () => undefined,
    };
    const preparedSql: string[] = [];
    let batch: readonly D1PreparedLike[] | undefined;
    const db: D1Like = {
      prepare(sql) {
        preparedSql.push(sql);
        return prepared;
      },
      async batch(statements) {
        batch = statements;
      },
    };

    await applySchema(db);

    expect(preparedSql).toEqual(SCHEMA);
    expect(batch).toHaveLength(SCHEMA.length);
  });
});
