import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { SCHEMA, SCHEMA_VERSION } from './schema.js';

/**
 * The migration `wrangler` applies and the array the tests run against are one
 * schema.
 *
 * Two hand-maintained copies is the oldest way to deploy a table the code does
 * not believe in, and the failure is silent in the worst direction: every test
 * passes against `SCHEMA`, and production has the other one. So the `.sql` is
 * generated by `tools/tribunal-migrations.mjs` and this asserts it did not drift
 * — which it will the first time somebody adds a column to `schema.ts` and
 * forgets that a deployment reads a file.
 */

const MIGRATION = join(
  dirname(fileURLToPath(import.meta.url)),
  '../migrations/0001_initial.sql',
);

describe('the D1 migration is the schema', () => {
  const text = readFileSync(MIGRATION, 'utf8');

  it('carries every statement, in order', () => {
    // Containment and ordering rather than re-parsing. Splitting the file back
    // into statements would need a `;` split, which is precisely what
    // `schema.ts` exists as a list to avoid — the semicolons inside a trigger's
    // `BEGIN … END` are part of the statement, and a test that cut them in half
    // would fail on a correct file and teach somebody to loosen this.
    let at = -1;

    for (const statement of SCHEMA) {
      const found = text.indexOf(statement.trim());
      expect(found, `missing from the migration: ${statement.trim().slice(0, 60)}…`).toBeGreaterThan(-1);
      expect(found, `out of order: ${statement.trim().slice(0, 60)}…`).toBeGreaterThan(at);
      at = found;
    }
  });

  it('adds nothing the schema does not have', () => {
    // The other direction, and the one containment alone cannot see: a statement
    // hand-added to the migration would deploy a table no test knows about.
    const statementLines = text
      .split('\n')
      .filter((line) => !line.startsWith('--') && line.trim() !== '').length;
    const schemaLines = SCHEMA.flatMap((statement) => statement.trim().split('\n')).length;

    expect(statementLines).toBe(schemaLines);
  });

  it('names the version it was generated from', () => {
    expect(text).toContain(`Schema version ${SCHEMA_VERSION}`);
  });

  it('says it is generated, so nobody edits it by hand', () => {
    // The comment is the only thing standing between this file and somebody
    // fixing production in it, which would pass every test in the repository.
    expect(text).toContain('Do not edit');
  });
});
