import { readFile } from 'node:fs/promises';
import { REVIEW_STYLES } from '../ui/styles.js';

/**
 * The two files a browser needs, and neither of them is React.
 *
 * The review surface is a React component tree, and a `node:http` server cannot
 * hand a browser a component tree. Something has to bundle it. That something is
 * **not this package** — [`tools/page-agents.mjs`](../../../../tools/page-agents.mjs)
 * records the rule and the reason: a bundler is not a thing a consumer of a
 * visual-regression tool should install, and `tools/shape.check.ts` refuses build
 * tools in any package's dependencies. So the bundling happens at this
 * repository's build time and the package ships the result, exactly as the four
 * page agents do.
 *
 * What is left here is the page that loads it: a document, the stylesheet inlined,
 * and the configuration the entry reads. The configuration goes in a
 * `application/json` script rather than into the bundle, because the endpoint and
 * the reviewer are properties of a *deployment* and the bundle is built once for
 * all of them.
 *
 * **No token is ever written into this page.** The review token promotes
 * baselines; a token in a page is a token in everybody's devtools. The browser
 * calls the same origin with no credential at all and the host attaches the
 * capability its own `authorize` granted — the rule is stated once in
 * [`next.ts`](../next.ts) and this file is downstream of it, not a second opinion.
 */

export interface ReviewPageOptions {
  /** Where the API is mounted, as the browser will address it. `''` is same-origin. */
  readonly endpoint: string;
  /** Recorded on every decision. There are no accounts here; this is a name. */
  readonly reviewer?: string;
}

export function reviewPage(options: ReviewPageOptions): string {
  const configuration = JSON.stringify({
    endpoint: options.endpoint,
    reviewer: options.reviewer ?? 'reviewer',
  });

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#181b1d">
<title>Variance Authority — review</title>
<style>/* This document's own reset, which is why it is here and not in
   REVIEW_STYLES: an operator injects that sheet into a page this package did not
   write, and a component stylesheet that reaches out and restyles the document
   body is a rude guest. This document is ours. Its shell is a hundred dynamic
   viewport units tall, so a default body margin overflows it by exactly twice
   the margin — a scrollbar on the one page whose whole claim is that it does
   not scroll. */
body { margin: 0; }
${REVIEW_STYLES}</style>
</head>
<body>
<div id="variance-review"></div>
<script type="application/json" id="variance-config">${safely(configuration)}</script>
<script type="module" src="ui/review.js"></script>
</body>
</html>
`;
}

/**
 * The bundle, or a script that says why there isn't one.
 *
 * A missing bundle means `tools/tribunal-ui.mjs` did not run — a build-ordering
 * problem in this repository, or an install from a tree that was never built. The
 * alternative to saying so is a blank page and a 404 in a console nobody opened,
 * so the failure is delivered as the script it replaces and lands in the document
 * where a reviewer will see it.
 */
export async function uiAsset(): Promise<string> {
  const from = new URL('../ui/review.bundle.js', import.meta.url);
  const bundle = await readFile(from, 'utf8').catch(() => null);
  if (bundle !== null) return bundle;

  return `document.getElementById('variance-review').textContent = ${JSON.stringify(
    'The review surface was never bundled. `dist/ui/review.bundle.js` is generated by ' +
      '`tools/tribunal-ui.mjs` at build time and this install does not have it. Run `yarn build` ' +
      'in the repository, or install a published @variance-authority/tribunal rather than a ' +
      'source checkout. The JSON API on this service is unaffected.',
  )};`;
}

/**
 * `</script>` inside a JSON string ends the script element, whatever the JSON
 * thinks. One replacement, because the value is `JSON.stringify` output and the
 * only sequence that can close the element is this one.
 */
function safely(json: string): string {
  return json.replace(/<\//g, '<\\/');
}
