import { readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

/**
 * The tree-sitter grammars are droppable, and stay droppable.
 *
 * Five of the crate's dependencies are C parsers generated by somebody else and
 * compiled by whatever `cc` the machine has, which is a way for the build to
 * fail that the rest of the crate does not have. Losing the scanner over them
 * would be the wrong trade — it is mostly oxc, and oxc reads the languages this
 * product is about — so `native/build.mjs` retries a failed build with
 * `--no-default-features` and ships a binary without them. That costs the
 * acceleration of Python, Rust, Java, Kotlin and Swift, which fall back to the
 * JavaScript readers that are the implementation of record anyway.
 *
 * The arrangement is three edits apart and the failure is silent in the
 * direction that matters: a sixth grammar added as an ordinary dependency
 * compiles fine, and the fallback it is not part of stops being a fallback —
 * `--no-default-features` then fails for the same reason the first attempt did,
 * and nobody finds out until a release does.
 */
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const NATIVE = join(ROOT, 'packages', 'sense', 'native');

const cargo = readFileSync(join(NATIVE, 'Cargo.toml'), 'utf8');

/** One TOML table's lines, by the header that opens it. */
function table(name: string): string[] {
  const lines = cargo.split('\n');
  const at = lines.indexOf(`[${name}]`);
  expect(at, `Cargo.toml has no [${name}]`).toBeGreaterThan(-1);
  const rest = lines.slice(at + 1);
  const end = rest.findIndex((line) => line.startsWith('['));
  return end === -1 ? rest : rest.slice(0, end);
}

describe('the tree-sitter grammars', () => {
  const declared = table('dependencies').filter((line) => line.startsWith('tree-sitter'));

  it('are dependencies at all', () => {
    expect(declared.length).toBeGreaterThan(1);
  });

  it.each(declared)('%s is optional', (line) => {
    expect(line).toContain('optional = true');
  });

  // Not a subset: a grammar left out of the feature is a grammar the fallback
  // still tries to compile, which is the whole failure this guards.
  it('are the whole `grammars` feature', () => {
    const feature = cargo.slice(cargo.indexOf('grammars = ['));
    const listed = [...feature.slice(0, feature.indexOf(']')).matchAll(/"dep:([^"]+)"/g)].map(
      (found) => found[1],
    );
    expect(listed.sort()).toEqual(declared.map((line) => line.split(' ')[0]).sort());
  });

  it('are on unless something asks otherwise', () => {
    expect(table('features')).toContain('default = ["grammars"]');
  });

  it('are what the build drops rather than failing on', () => {
    expect(readFileSync(join(NATIVE, 'build.mjs'), 'utf8')).toContain('--no-default-features');
  });

  // The method has to exist on a binary built without them, because `record.ts`
  // reaches an addon missing it through a different branch than an addon that
  // answers nothing — and only the second is the branch a machine with no addon
  // at all has already worn smooth.
  it('leave `readLanguage` answering nothing rather than gone', () => {
    const lib = readFileSync(join(NATIVE, 'src', 'lib.rs'), 'utf8');
    expect(lib).toContain('#[cfg(not(feature = "grammars"))]');
    expect(lib.slice(lib.indexOf('#[cfg(not(feature = "grammars"))]'))).toContain(
      'pub fn read_language',
    );
  });
});
